### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by frankyjuang** [BranchMetrics/web-branch-deep-linking-attribution#688]
Any plans for types?

**Comment by jnsdls** [comment]
@frankyjuang I needed the same, just opened a PR in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44154

Once that gets merged you should be able to use `@type/branch-sdk`

**Comment by jnsdls** [comment]
@frankyjuang https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44154 just got merged so you should be able to get `@types/branch-sdk` from npm now.

**Comment by frankyjuang** [comment]
awesome thanks
