### ISSUE TITLE
Web SDK necessary for mobile only support?

### ISSUE THREAD

**Issue by gustiando** [BranchMetrics/web-branch-deep-linking-attribution#793]
Hi,

Out team have been striving to understand how most things fit together in Branch.io, and fortunately we were finally able to get our iOS app properly deep linked from an email hyperlink. We're super happy about that :)

Although email-to-app is working as a charm, I was disappointed to realize that clicking on the email hyperlink from my desktop computer is no longer working. Though it was before we did the whole ESP Tracking Domain CNAME change over to Branch.

What's happening now is that once we click on the email from desktop, it resolves to something like [this](https://www.vts.com/?%243p=e_md&%24original_url=http%3A%2F%2Fapp.vts.com%2Flease%2Fdeals%2F348832%3F%2524deep_link%3Dtrue&_branch_match_id=823989613865622196&utm_medium=Email%20Mandrill&_branch_referrer=H4sIAAAAAAAAAxVN7QrDIAx8mvRfFYyDUihjMPYaIjO0MmuDpn3%2BpXBwd3Afmwj32dpL%2BpjoGoW65LqayGxKrj%2BL%2FATnkRcKexpUHi2vucYSzlaWTeuAL3Afxd3RHfM9dnWFYiflRLF0ZfTThA5Qkw%2FnExGH%2BwDwLe2kP0WH4aaIAAAA). We see that `original_url` is what we were hoping Branch to resolve, then redirect to in this desktop scenario, but that doesn't seem to be the case. Are we misunderstanding something?

The reason I'm asking here in addition to waiting for the support team to respond is because I wonder: **Are we missing yet another integration with Web SDK to get it all working properly? or is something just misconfigured?**

Thank you

**Comment by jf-branch** [comment]
Hi @gustiando, 

Sorry for the delay here, as I hope you were able to resolve the issue, if not, i would strongly suggest to creating a support ticket through: https://help.branch.io/using-branch/page/submit-a-ticket as our support team will help provide guidance.
