### ISSUE TITLE
Requests to `https://api2.branch.io/v1/open` give invalid Content-Type 'text/javascript charset=UTF-8'

### ISSUE THREAD

**Issue by mileszim** [BranchMetrics/web-branch-deep-linking-attribution#794]
<img width="474" alt="Screen Shot 2022-04-14 at 12 45 33 AM" src="https://user-images.githubusercontent.com/1849508/163338827-255da75a-50ef-4e05-a95b-606e8922b2a9.png">

It should be returning `application/javascript; charset=UTF-8`.
 - It shows **text**/javascript` instead of **application**/javascript
 - it is missing the semicolon `;` after `application/javascript`.

The effect of this is an invalid check fail in Chrome:
<img width="1417" alt="Screen Shot 2022-04-14 at 12 48 48 AM" src="https://user-images.githubusercontent.com/1849508/163338960-816f0650-7250-4eb2-adc2-6a4e056e4e44.png">

I believe this is a server misconfiguration.

**Comment by JagadeeshKaricherla-branch** [comment]
Issue already fixed.
