### ISSUE TITLE
"branch-journeys-top" lost margin-top style when navigating to next page  

### ISSUE THREAD

**Issue by rycustodio** [BranchMetrics/web-branch-deep-linking-attribution#801]
If there is a bug or error in this repo, please file the issue here. 

<div class="branch-journeys-top"></div> only works on the landing page but when the user navigates to other pages, the style - margin-top on the parent div of **branch-journeys-top** disappeared and the overlaps return.

What is the workaround for this? 
 
If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by jf-branch** [comment]
Hi @rycustodio I would recommend creating a ticket with out support team https://help.branch.io/using-branch/page/submit-a-ticket as they can ask the additional information and help resolve your issue.
