### ISSUE TITLE
please publish #805 to npm

### ISSUE THREAD

**Issue by Yuddomack** [BranchMetrics/web-branch-deep-linking-attribution#809]
Hi! I'm using branch-sdk with [vite](https://vitejs.dev/), but there is one problem.

vite runs as esbuild in dev phase and build as rollup

in rollup with commonjs plugin (build time), branch-sdk's global is converted to globalThis
like this

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/41747333/174049112-83c80dfc-082f-48bd-ad12-bc9db2a10491.png">

but dev phase does not support this.
in module isolation, `window`, `global`, `this` is undefined so $jscomp.global is always undefined
(yes, maybe this is a problem to be solved in esbuild)

<img width="765" alt="image" src="https://user-images.githubusercontent.com/41747333/174049952-cacb2134-a697-4055-80b5-5a8e403f2502.png">

While looking for a solution to this, 
I found that the contents of `dist/build` after #805 and version 2.62.0 of npm are different.

and applying #805 directly, solved problem.

so Please consider a new deployment (even if rc version!)

**Comment by JagadeeshKaricherla-branch** [comment]
@Yuddomack release 2.63.0 has #805 changes.

**Comment by Yuddomack** [comment]
@JagadeeshKaricherla-branch 
I checked working! thanks!
