### ISSUE TITLE
iOS 12 Safari browser - Branch latest JS SyntaxError

### ISSUE THREAD

**Issue by stephendavid** [BranchMetrics/web-branch-deep-linking-attribution#821]
### Describe the bug

When loading branch URL from Safari IOS 12 version, we are facing syntax error from branch library js file.

### Steps to reproduce

1. Create branch URL through API V1 with custom data.
2. Load the URL on iOS 12 Safari browser
3. Developer tool - Console screen we can able see the error due to this we couldn't able to get branch data
the 

### Expected Behavior

It should return the custom data attachment with the URL

### SDK version used (`window.branch.sdk`)

Latest

### Environment

iOS 12 Safari

**Comment by JagadeeshKaricherla-branch** [comment]
Fixed in 2.67.0 release
