### ISSUE TITLE
Extension mv3 support

### ISSUE THREAD

**Issue by hoyangtsai** [BranchMetrics/web-branch-deep-linking-attribution#833]
### Describe the feature

Suppose running the branch in the background which is able to generate an universal link between content and popup.

There are errors when init the SDK since mv3 background running with [service worker](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#service-workers) only.

**Comment by JagadeeshKaricherla-branch** [comment]
@hoyangtsai can you provide us more info about the issue

**Comment by hoyangtsai** [comment]
I have an extension running by react and redux. I want to the data to be persistent, the utils to be used whenever needed, so the branch-sdk will be initialized at the background. 
When I need a deep link, I dispatch an action to the background to create it by branch.

**Comment by hoyangtsai** [comment]
BTW now I init the sdk at the background, and even disabled the event tracking.

```js
// init Branch
branch.init(
  'key_live_YOUR_KEY_GOES_HERE',
  {
    tracking_disabled: true,
  }
);
```

I got this error.
![console-error](https://user-images.githubusercontent.com/1687532/199658764-44fb9063-c868-4f6c-a19f-3c0998556892.png)

![error-code](https://user-images.githubusercontent.com/1687532/199658817-a6f00dfb-1b3a-46a8-9d44-4be8ac618b20.png)

**Comment by JagadeeshKaricherla-branch** [comment]
Manifest version 3 does not support background pages, it only supports service workers. That means you have no DOM or Document or window.
Currently Branch web-sdk doesn’t support scenarios where document is not available.
We have an archived manifest v2 based chrome extension : https://github.com/BranchMetrics/branch-chrome-extension
