### ISSUE TITLE
experiments that require multiple visits does not work on IOS devices

### ISSUE THREAD

**Issue by electather** [BranchMetrics/web-branch-deep-linking-attribution#902]
### Describe the bug

all of our experiments that require tracking users across visits ( eg. >2 visits ) does not work with the SDK.
after looking into the responses, I noticed `browser_fingerprint_id` keeps changing on IOS devices, but not on Android devices. 

### Steps to reproduce

1. set device to any IOS (eg. iphone 12)
2. refresh 
3. `browser_fingerprint_id` has changed

### Expected Behavior

`browser_fingerprint_id` should stay consistent across visits

### SDK version used (`window.branch.sdk`)

2.74.0

### Environment

Chrome 113

**Comment by JagadeeshKaricherla-branch** [comment]
not able to reproduce this.
Can try clearing the application storage before switching the user agent/ device

**Comment by electather** [comment]
we're using branch live on `what3words.com`
I attached a video trying to reproduce the problem. clearing the storage has no effect.

https://github.com/BranchMetrics/web-branch-deep-linking-attribution/assets/33129195/0bd93045-32ee-4b8e-a7ba-f5b1572bb787
